In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
sent=['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words', 
    'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
voc_size = 10000

#### One Hot Representation

In [34]:
one_hot_repre = [one_hot(words,voc_size) for words in sent]
one_hot_repre 

[[7423, 9890, 5885, 692],
 [7423, 9890, 5885, 6933],
 [7423, 6880, 5885, 8399],
 [4322, 9618, 870, 639, 1994],
 [4322, 9618, 870, 639, 2094],
 [8195, 7423, 6897, 5885, 9797],
 [7364, 2917, 7858, 639]]

#### Word Embedding Representation

In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [36]:
import numpy as np

In [37]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repre,padding="pre",maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 7423, 9890, 5885,  692],
       [   0,    0,    0,    0, 7423, 9890, 5885, 6933],
       [   0,    0,    0,    0, 7423, 6880, 5885, 8399],
       [   0,    0,    0, 4322, 9618,  870,  639, 1994],
       [   0,    0,    0, 4322, 9618,  870,  639, 2094],
       [   0,    0,    0, 8195, 7423, 6897, 5885, 9797],
       [   0,    0,    0,    0, 7364, 2917, 7858,  639]], dtype=int32)

In [44]:
embedded_docs.shape

(7, 8)

In [38]:
dim = 10

In [39]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 7423, 9890, 5885,  692], dtype=int32)

In [42]:
model.predict(embedded_docs)[0]

2023-12-22 01:33:55.790169: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


array([[ 0.0165095 ,  0.04990328,  0.00157934, -0.04056182, -0.0119241 ,
        -0.0078639 ,  0.01899024, -0.00205231, -0.0440761 , -0.04268888],
       [ 0.0165095 ,  0.04990328,  0.00157934, -0.04056182, -0.0119241 ,
        -0.0078639 ,  0.01899024, -0.00205231, -0.0440761 , -0.04268888],
       [ 0.0165095 ,  0.04990328,  0.00157934, -0.04056182, -0.0119241 ,
        -0.0078639 ,  0.01899024, -0.00205231, -0.0440761 , -0.04268888],
       [ 0.0165095 ,  0.04990328,  0.00157934, -0.04056182, -0.0119241 ,
        -0.0078639 ,  0.01899024, -0.00205231, -0.0440761 , -0.04268888],
       [ 0.01144468,  0.04500861, -0.01309341,  0.04445628, -0.01660788,
        -0.01517491, -0.03774726, -0.01410175, -0.03484107,  0.00898546],
       [ 0.00279276,  0.0178006 ,  0.04898221, -0.02191588, -0.03724471,
        -0.0006809 , -0.04326351,  0.03388273, -0.03244851,  0.01127494],
       [ 0.04262588, -0.02082784,  0.04170613, -0.03005501, -0.03803331,
         0.00820342, -0.04057308,  0.03935296

In [43]:
model.predict(embedded_docs).shape

(7, 8, 10)